# Not sure if we can plop this in and build it with clang, so for now, just
# compile with binaries built by gcc... 
ifeq ($(TOOLCHAIN),gcc)
DEPS += libmspbuiltins
else # TOOLCHAIN != gcc

# libmspware is special because it has to be compiled by GCC, not Clang,
# even if the app is built with Clang
CFLAGS += -I$(LIB_ROOT)/libmspware/src/include
LFLAGS += -L$(LIB_ROOT)/libmspware/bld/gcc
LIBS += -lmspware

endif # TOOLCHAIN != gcc

